---
title: "Test CellMixS metrics on Splatter synthetic data"
author: "S. Carmona"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'test_CellMixS.html'))})
---

# Introduction
  
Testing CellMixS batch effect metrics

In these test synthetic datasets, there is no cell type-specific signal, so we'll simulate those using 
splatter https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splatter.html


# R environment

Get and load some useful packages
```{r message=F, warning=F,results=F, eval=T}
renv::restore()

if (!require("remotes", quietly = TRUE))
    install.packages("remotes")
library(remotes)

if (!require("tidyr", quietly = TRUE))
install.packages("tidyr")

if (!require("scIntegrationMetrics", quietly = TRUE))
install_github("carmonalab/scIntegrationMetrics") #calculates LISI and Silhouette

if (!requireNamespace("BiocManager"))
    install.packages("BiocManager")

BiocManager::install("CellMixS")

BiocManager::install("splatter")

```


```{r message=F, warning=F,results=F}
library(dplyr)
library(ggplot2)
library(tidyr)
library(scIntegrationMetrics)
library(patchwork)
library(CellMixS)
library(splatter)

seed = 1234
set.seed(seed)
```

```{r}
# Load required packages
suppressPackageStartupMessages({
    library(SingleCellExperiment)
    library(dplyr)
    library(purrr)
    library(ggplot2)
    library(scater)
})
```



Prepare extreme heterogeneous datasets (batch effects + different subtype composition) to evaluate metrics

```{r}
test.list <- list()
mySeed <- 123

ncellsBatchBig <- 500
ncellsBatchSmall <- ncellsBatchBig/2 

set.seed(mySeed)

test <- splatSimulate(batchCells = c(ncellsBatchBig, ncellsBatchSmall*2, ncellsBatchSmall*2), group.prob = c(0.5, 0.5), 
                            method = "groups", verbose = FALSE, batch.facScale= 0.1, batch.facLoc=0.1 ) # see ?SplatParams  de.facLoc=0.2, de.facScale=0.2
test <- test[,!(test$Batch=="Batch2" & test$Group=="Group1")]
test <-  test[,!(test$Batch=="Batch3" & test$Group=="Group2")]
table(test$Group,test$Batch)
test <- logNormCounts(test)
test <- runPCA(test, ncomponents = 2, ntop=500)
test <- evalIntegration(test, metrics = c("isi", "cms"), group = "Batch", k = 20, n_dim = 2, cell_min = 5, weight = F)
plotPCA(test, shape_by = "Group", colour_by = "Batch") + ggtitle(sprintf("cms %.2f; lisi %.2f",mean(test$cms_smooth),mean(test$isi)))

test.list[["batch20_balanced"]] <- test
```

```{r}
ncellsBatchBig <- 500
ncellsBatchSmall <- ncellsBatchBig/2 

set.seed(mySeed)

test <- splatSimulate(batchCells = c(ncellsBatchBig, ncellsBatchSmall*2, ncellsBatchSmall*2), group.prob = c(0.5, 0.5), 
                            method = "groups", verbose = FALSE, batch.facScale= 0, batch.facLoc=0 ) # see ?SplatParams  de.facLoc=0.2, de.facScale=0.2
test <- test[,!(test$Batch=="Batch2" & test$Group=="Group1")]
test <-  test[,!(test$Batch=="Batch3" & test$Group=="Group2")]
table(test$Group,test$Batch)
test <- logNormCounts(test)
test <- runPCA(test, ncomponents = 2, ntop=500)
test <- evalIntegration(test, metrics = c("isi", "cms"), group = "Batch", k = 20, n_dim = 2, cell_min = 5, weight = F)
plotPCA(test, shape_by = "Group", colour_by = "Batch") + ggtitle(sprintf("cms %.2f; lisi %.2f",mean(test$cms_smooth),mean(test$isi)))

test.list[["batch0_balanced"]] <- test
```




```{r}

ncellsBatchBig <- 500
ncellsBatchSmall <- ncellsBatchBig/2 

set.seed(mySeed)

test <- splatSimulate(batchCells = c(ncellsBatchBig, ncellsBatchSmall*2, ncellsBatchSmall*2), group.prob = c(0.5, 0.5), 
                            method = "groups", verbose = FALSE, de.facLoc=0, de.facScale=0, batch.facScale= 0, batch.facLoc=0 ) # see ?SplatParams  de.facLoc=0.2, de.facScale=0.2
test <- test[,!(test$Batch=="Batch2" & test$Group=="Group1")]
test <-  test[,!(test$Batch=="Batch3" & test$Group=="Group2")]
table(test$Group,test$Batch)
test <- logNormCounts(test)
test <- runPCA(test, ncomponents = 2, ntop=500)
#plotPCA(test, shape_by = "Group", colour_by = "Batch") 
test <- evalIntegration(test, metrics = c("isi", "cms"), group = "Batch", k = 20, n_dim = 2, cell_min = 5, weight = F)
plotPCA(test, shape_by = "Group", colour_by = "Batch") + ggtitle(sprintf("cms %.2f; lisi %.2f",mean(test$cms_smooth),mean(test$isi)))

test.list[["overcorrected_balanced"]] <- test

```


```{r}
ncellsBatchBig <- 800
ncellsBatchSmall <- 100

set.seed(mySeed)

test <- splatSimulate(batchCells = c(ncellsBatchBig, ncellsBatchSmall*2, ncellsBatchSmall*2), group.prob = c(0.5, 0.5), 
                            method = "groups", verbose = FALSE, batch.facScale= 0, batch.facLoc=0 ) # see ?SplatParams  de.facLoc=0.2, de.facScale=0.2
test <- test[,!(test$Batch=="Batch2" & test$Group=="Group1")]
test <-  test[,!(test$Batch=="Batch3" & test$Group=="Group2")]
table(test$Group,test$Batch)
test <- logNormCounts(test)
test <- runPCA(test, ncomponents = 2, ntop=500)
#plotPCA(test, shape_by = "Group", colour_by = "Batch") 
test <- evalIntegration(test, metrics = c("isi", "cms"), group = "Batch", k = 20, n_dim = 2, cell_min = 5, weight = F)
plotPCA(test, shape_by = "Group", colour_by = "Batch") + ggtitle(sprintf("cms %.2f; lisi %.2f",mean(test$cms_smooth),mean(test$isi)))

test.list[["batch0_unbalanced"]] <- test

```

```{r}

lapply(test.list,function(test){
  plotPCA(test, shape_by = "Group", colour_by = "Batch") + ggtitle(sprintf("cms %.2f; lisi %.2f",mean(test$cms_smooth),mean(test$isi))) | visHist(test,metric = c("cms"))
})

```


```{r}
lapply(test.list,function(test){
  visOverview(test, "Batch", metric = c("cms", "isi"), other_var = "Group")    
})
```

```{r}
ndim=2
test.list.names <- names(test.list)
seurat.list <- lapply(test.list.names, function(name){
    sce <- test.list[[name]]
    #rownames(sce) <- paste0("feature",1:nrow(sce))
    #obj <- as.Seurat(sce, counts = "counts", data = NULL)
    obj <- RenameAssays(obj, originalexp = 'RNA')
    #obj <- NormalizeData(obj) %>% ScaleData() %>% RunPCA(npcs=ndim)
})
names(seurat.list) <-test.list.names

saveRDS(seurat.list,"synthetic.seurat.rds")
```






