---
title: "Explore integration metrics on the Iris dataset"
author: "M. Andreatta and S. Carmona"
date: "26/08/2022"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'iris_integrationMetrics.html'))})
---

# Introduction
  
Here we will explore commonly used metrics to evaluate the quality of single-cell omics data integration, including LISI and silhouette coefficient.

Maybe use simulated dataset https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splatter.html

# R environment

Get and load some useful packages
```{r message=F, warning=F,results=F, eval=T}
renv::restore()

if (!require("remotes", quietly = TRUE))
    install.packages("remotes")
library(remotes)

if (!require("tidyr", quietly = TRUE))
install.packages("tidyr")

if (!require("scIntegrationMetrics", quietly = TRUE))
install_github("carmonalab/scIntegrationMetrics") #calculates LISI and Silhouette

```


```{r message=F, warning=F,results=F}
library(dplyr)
library(ggplot2)
library(tidyr)
library(scIntegrationMetrics)
library(patchwork)

seed = 1234
set.seed(seed)
```




